-- Question 1

SELECT * FROM EMP WHERE EMP_MGR = 100 AND 30 > ANY (SELECT DATEDIFF(STR_TO_DATE(EMP_HIRE_DATE, '%m/%d/%Y'), STR_TO_DATE(EMP_DOB, '%m/%d/%Y'))/365 AS AGE FROM EMP);

-- Question 2

SELECT EMP_MGR, COUNT(*) FROM EMP GROUP BY EMP_MGR;

-- Question 3

SELECT EMP_MGR, COUNT(*) AS COUNT FROM EMP GROUP BY EMP_MGR ORDER BY COUNT DESC LIMIT 1;

-- Question 4



-- Question 5

SELECT CUSTOMER.* FROM INVOICE JOIN CUSTOMER ON CUSTOMER.CUS_CODE = INVOICE.CUS_CODE ORDER BY INV_TOTAL DESC LIMIT 1;